# Generated by Django 3.0.8 on 2020-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='activities',
            field=models.ManyToManyField(blank=True, to='dev_site01.List'),
        ),
    ]
