# Generated by Django 3.0.8 on 2020-07-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0004_list_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='project',
        ),
    ]
