# Generated by Django 3.0.8 on 2020-07-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0005_remove_list_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_site01.Projects'),
        ),
    ]
