# Generated by Django 3.0.8 on 2020-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0006_list_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
