# Generated by Django 3.0.8 on 2020-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0007_auto_20200702_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
