# Generated by Django 3.0.8 on 2020-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0008_auto_20200702_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
