# Generated by Django 3.0.8 on 2020-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0009_projects_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
