# Generated by Django 3.0.8 on 2020-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0010_projects_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
