# Generated by Django 3.0.8 on 2020-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0012_userprofile_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Outstanding_requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='challenges',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='website_owner',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
