# Generated by Django 3.0.8 on 2020-07-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0013_auto_20200703_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Outstanding_requirements',
            new_name='outstanding_requirements',
        ),
    ]
