# Generated by Django 3.0.8 on 2020-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0015_projects_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='start_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
