# Generated by Django 3.0.8 on 2020-07-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0016_projects_start_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='start_date2',
        ),
    ]
