# Generated by Django 3.0.8 on 2020-07-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dev_site01', '0017_remove_projects_start_date2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_of_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=10000)),
                ('done', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('group_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_related_to_task', to='dev_site01.Group_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group_project',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='task_related_to_project', to='dev_site01.Task'),
        ),
        migrations.AddField(
            model_name='group_project',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
