# Generated by Django 3.0.8 on 2020-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0018_auto_20200703_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_project',
            name='project_title',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
