# Generated by Django 3.0.8 on 2020-07-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0020_auto_20200703_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assign_user_to_task',
        ),
    ]
