# Generated by Django 3.0.8 on 2020-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0023_auto_20200706_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
