# Generated by Django 3.0.8 on 2020-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0024_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
