# Generated by Django 3.0.8 on 2020-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0025_auto_20200706_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_project',
            name='add_collaborator',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
