# Generated by Django 3.0.8 on 2020-07-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0029_auto_20200706_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assign_user_to_task',
            new_name='assign_collaborator_to_task',
        ),
    ]
