# Generated by Django 3.0.8 on 2020-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0030_auto_20200706_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='label_colour',
            field=models.CharField(choices=[('primary', 'primary'), ('dark', 'dark'), ('warning', 'warning'), ('info', 'info'), ('secondary', 'secondary'), ('danger', 'danger'), ('light', 'light'), ('success', 'success')], default='primary', max_length=90),
        ),
    ]
