# Generated by Django 3.0.8 on 2020-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0031_collaborators_label_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborator_working_on_group_project', to='dev_site01.Collaborators'),
        ),
    ]
