# Generated by Django 3.0.8 on 2020-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0035_collaborators_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group_project',
        ),
    ]
