# Generated by Django 3.0.8 on 2020-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0036_remove_userprofile_group_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_project',
            field=models.ManyToManyField(to='dev_site01.Group_project'),
        ),
    ]
