# Generated by Django 3.0.8 on 2020-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_site01', '0037_userprofile_group_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='label_colour',
            field=models.CharField(choices=[('primary', 'primary'), ('dark', 'dark'), ('warning', 'warning'), ('info', 'info'), ('secondary', 'secondary'), ('danger', 'danger'), ('light', 'light')], default='warning', max_length=90),
        ),
    ]
